version: 2
jobs:
  testflight-dev:
    macos:
      xcode: "11.1.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose

      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
          no_output_timeout : 60m
 
version: 2
jobs:
 deploy-dev:
    environment:
      FASTLANE_LANE: dev
      
workflows:
  version: 2
  testflight-dev:
    jobs:
      - deploy-dev:
         filters:
           tags:
             only: /release\/dev-.*/
           branches:
             ignore: /.*/
